### ISSUE TITLE
Wrong colour name in "how to play"

### ISSUE THREAD

**Issue by Jameskmonger** [Q42/0hh1#30]
The "how to play" section at [0hh1.com](http://0hh1.com/) refers to red and blue, but is in fact red and yellow.

**Comment by Primigenus** [comment]
We changed the colours in tribute to the victims of the Brussels terrorist attacks that happened yesterday. Don't worry, things will be back to normal soon... for Brussels too, hopefully.

**Comment by Jameskmonger** [comment]
Ah, okay. I didn't know that the colour change was intentional.
